### ISSUE TITLE
Cannot create scaffold

### ISSUE THREAD

**Issue by Harushii18** [RXRider1451/SD_Project_Website#9]
A lot of team members have been having issues with the creation of the scaffold.

**Comment by Harushii18** [comment]
### Kameron's solution:

1. Use the command in the project location terminal: 
`Rails g scaffold TableName AttributeName:AttributeDataType --force`
You can add as many attributes as you want
`--force` is not a compulsory command. It is only used when the controllers/ views have already been made with the same name and need to be overwritten (do an override)

2. Unlink all foreign keys to that table in MySQL workbench by removing the foreign key links. Once you are done, drop the table 

3. Use the command in your project location terminal: `rails db:migrate` 

4. Now you will notice that a controller, as well as HTML files in the views have been created for you for editing and creating. All that will need to be done is to improve the look of it using bootstrap.

_**Please note that the destroy function currently does not work. This is still to be worked on, therefore this issue will remain open.**_

**Comment by KiyolinPerumal** [comment]
Update on destroy function

The "link_to" function provided by ruby does not seem to be working properly.

Temp Solution
Use "button_to" function instead. 
However, note that while this performs the actual deletion. It does not show the confirmation dialog to destroy
